config/routes.rb
Rails.application.routes.draw do
  root to: 'people#index'
  resources :people, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :planet
  belongs_to :race
  has_many :pilots
  has_many :starcrafts, through: :pilots

  validates :name, :height, :weight, :dob, :hair, :skin, :eye, :gender, presence: true
end

app/models/pilot.rb
class Pilot < ApplicationRecord
  belongs_to :person
  belongs_to :starcraft
end

app/models/planet.rb
class Planet < ApplicationRecord
  has_many :people

  validates :name, presence: true
end

app/models/race.rb
class Race < ApplicationRecord
  has_many :people

  validates :kind, presence: true
end

app/models/starcraft.rb
class Starcraft < ApplicationRecord
  has_many :pilots

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    if params[:query].present?
      @people = Person.where("people.name @@ :query", query: "%#{params[:query]}%")
    else
      @people = Person.all.order(:name)
    end
  end

  def show
    @person = Person.find(params[:id])
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Galactic Imperialist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('death-star.png') %>
  </head>

  <body>
    <%= render 'shared/banner' %>
    <%= yield %>
  </body>
</html>

app/views/people/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-lg-3 list-fixed py-4">
      <h3>List of characters:</h3>
      <%= render "shared/search_bar" %>
      <div class="list-wrapper">
        <ul>
          <% @people.each do |person| %>
            <%= link_to person_path(person), remote: true do %>
              <li>
                <%= person.name %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-12 col-lg-9 py-4" id="show-person">
      <%= render "shared/crawl_animation" %>
    </div>
  </div>
</div>

app/views/people/show.js.erb
var person_div = document.querySelector("#show-person");
document.querySelector("#show-person").innerHTML="<%= j render partial: 'shared/show_person', locals: { person: @person } %>";

app/views/shared/_banner.html.erb
<div class="banner">
  <%#= link_to '<h1>The Galactic</h1><h1>&emsp;&emsp;imperia<span>List</span></h1>'.html_safe, root_path %>
  <h1><a href="/">The Galactic</a></h1><h1>&emsp;&emsp;<a href="/">imperia<span>List</a></span></h1>
</div>

app/views/shared/_common_sentence.html.erb
My name is <%= person.name %>, 
I'm a <%= link_to person.race.kind, "https://starwars.fandom.com/wiki/#{person.race.kind}", target: "_blank" %> 
from <%= link_to person.planet.name, "https://starwars.fandom.com/wiki/#{person.planet.name}", target: "_blank" %>.

app/views/shared/_crawl_animation.html.erb
<div id="intro"> A long time ago, in a galaxy far,<br> far away....</div>
<div id="logo"></div>
<div id="scroller">
  <div>
    <p>
      This project was made by me, 
      David Pessanha, after 1 week 
      of hard work, debugging, coffee 
      and searching.
    </p>
    <p>
      During the battle, I've learned 
      new ways to do things and increased 
      my unit testing skills using RSPEC, 
      which is something I'm very proud of.
    </p>
    <p>
      It was a very fun project, I enjoyed 
      working on it a lot and I believe I did 
      my best!
    </p>
  </div>
</div>

app/views/shared/_greeting.html.erb
<% if person.starcrafts.length > 0 %>
  <% starships = person.starcrafts.map { |starcraft| starcraft.name } %>
  <p>
    <%= render "shared/common_sentence", person: person %> And I've already piloted: 
    <%= starships.join(', ').reverse.sub(',', ' and'.reverse).reverse %>.
  </p>
<% else %>
  <p>
    <%= render "shared/common_sentence", person: person %>
    And I've never piloted before.
  </p>
<% end %>

app/views/shared/_search_bar.html.erb
<div class="search-bar">
  <%= form_tag root_path, method: :get do %>
    <div class="d-flex">
      <%= link_to '<i class="fas fa-undo search-icon"></i>'.html_safe, root_path, class: "back-button" %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control search-input",
        placeholder: "Find a character",
        id:"search-inp"
      %>
      <%= button_tag '<i class="fas fa-search search-icon"></i>'.html_safe, type: 'submit', class: "search-button", id:"search-btn" %>
    </div>
  <% end %>
</div>

app/views/shared/_show_person.html.erb
<div class="row content-wrapper">
  <div class="col-md-12 col-lg-4 py-lg-4 py-md-0 ml-lg-5 ml-sm-0 content-avatar">
    <%= image_tag person.picture_url %>
  </div>
  <div class="col-md-12 col-lg-7 my-4 content-box d-flex flex-column justify-content-between">
    <div class="row">
      <div class="col-12">
        <div class="content-header">
          <h2><%= person.name.downcase %></h2><br>
          <%= render "shared/greeting", person: person %>
        </div>
      </div>
    </div>
    <div class="content-text">
      <div class="row">
        <div class="col-6">
          <h3>Homeworld:</h3>
          <p><%= person.planet.name %></p>
          <h3>Species:</h3>
          <p><%= person.race.kind %></p>
          <h3>Weight (Kg):</h3>
          <p><%= person.weight.upcase %></p>
          <h3>Hair:</h3>
          <p><%= person.hair.capitalize %></p>
        </div>
        <div class="col-6">
          <h3>Birth Year:</h3>
          <p><%= person.dob.upcase %></p>
          <h3>Gender:</h3>
          <p><%= person.gender.capitalize %></p>
          <h3>Height (cm):</h3>
          <p><%= person.height %></p>
          <h3>Eye:</h3>
          <p><%= person.eye.capitalize %></p>
        </div>
      </div>
    </div>
  </div>
</div>